-- Drop views first (if any)
DROP VIEW IF EXISTS public_questions CASCADE;
DROP VIEW IF EXISTS public_quiz_stats CASCADE;
DROP VIEW IF EXISTS user_quiz_history CASCADE;

-- Drop tables (in dependency order)
DROP TABLE IF EXISTS question_response CASCADE;
DROP TABLE IF EXISTS quiz_attempt CASCADE;
DROP TABLE IF EXISTS quiz_question CASCADE;
DROP TABLE IF EXISTS quiz CASCADE;
DROP TABLE IF EXISTS question_option CASCADE;
DROP TABLE IF EXISTS question_tag CASCADE;
DROP TABLE IF EXISTS question CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS subject CASCADE;
DROP TABLE IF EXISTS institution CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_music_setting CASCADE;
DROP TABLE IF EXISTS background_music CASCADE;
DROP TABLE IF EXISTS playlist_music CASCADE;
DROP TABLE IF EXISTS playlist CASCADE;

-- Drop types
DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS music_mood CASCADE;